sfdc_pra1/objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Event_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc_pra1/objects/Expensemember__c.object
<CustomObject>
    <fields>
        <fullName>Contrib_amount__c</fullName>
        <label>Contrib_amount</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expensemembers</relationshipLabel>
        <relationshipName>Expensemembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expensemembers</relationshipLabel>
        <relationshipName>Expensemembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensemember</label>
    <nameField>
        <displayFormat>Expensemember{0000}</displayFormat>
        <label>Expensemember_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expensemembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc_pra1/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc_pra1/classes/Expensecls.cls
public with sharing class Expensecls {
    public Expense__c expobj{get;set;}
    public List<Expensemember__c> memExp{get;set;}                         //List of Expense Member Object

    public Expensecls(ApexPages.StandardController controller) {
        expobj = (Expense__c)controller.getRecord();
        memExp = getExpMembers();
    }
    
    public List<Expensemember__c> getExpMembers(){
        return [Select Contrib_amount__c,Member__r.Name from Expensemember__c where Expense__c =: expobj.Id];
    }
}