sfdc_pra1/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Event_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc_pra1/objects/Expensemember__c.object
<CustomObject>
    <fields>
        <fullName>Contrib_amount__c</fullName>
        <label>Contrib_amount</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expensemembers</relationshipLabel>
        <relationshipName>Expensemembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expensemembers</relationshipLabel>
        <relationshipName>Expensemembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expensemember</label>
    <nameField>
        <displayFormat>Expensemember{0000}</displayFormat>
        <label>Expensemember_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expensemembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc_pra1/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdc_pra1/classes/ExpenseTest.cls
@isTest

public class ExpenseTest {
 public testMethod static void myTest(){
      
        Expense__c expense = new Expense__c();                                                         //Test Object expense 
        expense.Amount__c=1000;                                                                       //Test value for Amount field
        expense.Name='party';                                                                         //Test value for Event Name field
        insert expense;                                                                              //Inserting the test object expense
        
                                                         
        Member__c member = new Member__c();                                                          //Test Object member 
        member.Name='abc';                                                                           //Test value for Name Field
        member.Email__c='abc@abc.com';                                                                //Test value for Email field
        insert member;                                                                               //Inserting the test object member
        
        
        Expensemember__c expmem = new Expensemember__c();                                            //Test Object expmem
        expmem.Member__c=member.Id;                                                                  //Test value for member field
        expmem.Expense__c=expense.Id;                                                                //Test value for expense field
        expmem.Contrib_amount__c=100;                                                                //Test value for Contribution amount field
        insert expmem;                                                                               //Inserting the test object expmem 
        
        Expensecls expExt = new Expensecls (new ApexPages.StandardController(expense));              //pdfprintpreview Test object
        
        List<Expensemember__c> ge = new List<Expensemember__c>();
        ge = expExt.getExpMembers();
}
}